website/views.py
from flask import Blueprint, render_template, request, redirect, flash, jsonify, url_for
from flask_login import login_required, current_user
from .models import Note, User, Task, Reward
from .task_tracker import add_xp, subtract_xp, update_level
from . import db
import datetime
import json

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    return render_template("home.html", user=current_user)


@views.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    return render_template("profile.html", user=current_user)

@views.route('/rewards', methods=['GET', 'POST'])
@login_required
def rewards():
    return render_template("rewards.html", user=current_user)

@views.route('/notes', methods=['GET', 'POST'])
@login_required
def notes():
    if request.method == 'POST':
        note = request.form.get('note')
        if len(note) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!')
    
    return render_template("notes.html", user=current_user)


@views.route('/tasks', methods=['GET', 'POST'])
@login_required
def task():    
    return render_template("tasks.html", user=current_user)


@views.route('/add-task/<int:taskXp>', methods=['POST'])
def add_task(taskXp):
    task = request.form.get('task')
    if len(task) < 1:
        flash('Task name too short!', category='error')
    else:
        if taskXp == current_user.dailyXpValue:
            scheduling_interval = 'daily'
        elif taskXp == current_user.weeklyXpValue:
            scheduling_interval = 'weekly'
        elif taskXp == current_user.monthlyXpValue:
            scheduling_interval = 'monthly'
        new_task = Task(data=task, user_id=current_user.id, xp=taskXp, scheduling_interval=scheduling_interval)
        db.session.add(new_task)
        db.session.commit()
        flash('Task added!')
        print(new_task.is_done)
        print(new_task.scheduling_interval)
    return redirect(url_for("views.task"))


@views.route('/edit/<int:taskId>', methods=['GET', 'POST'])
def edit_tasks(taskId):
    task = Task.query.get(taskId)
    if request.method == "POST":
        task.data = request.form['task']
        db.session.commit()
        return redirect(url_for("views.task"))
    else:
        return render_template("edit-task.html", task=task, user=current_user)


@views.route('/check/<int:taskId>')
def check_tasks(taskId):
    checked_task = Task.query.get(taskId)
    checked_task.is_done = not checked_task.is_done
    if checked_task.is_done == True:
        add_xp(checked_task.xp)
    else:
        subtract_xp(checked_task.xp)
    db.session.commit()
    return redirect(url_for("views.task"))


@views.route('/delete/<int:taskId>')
def delete_tasks(taskId):
    task = Task.query.get(taskId)
    if task:
        if task.user_id == current_user.id:
            db.session.delete(task)
            db.session.commit()
            flash('Task deleted', category='error')
    
    return redirect(url_for("views.task"))


@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()
    
    return jsonify({})


@views.route('/add-reward', methods=['POST'])
def add_rewards():
    reward = request.form.get('reward')
    if len(reward) < 1:
        flash('Reward name too short!', category='error')
    else:
        new_reward = Reward(data=reward, user_id=current_user.id)
        db.session.add(new_reward)
        db.session.commit()
        flash('Reward added!')
    return redirect(url_for("views.rewards"))


@views.route('/check-reward/<int:rewardId>')
def check_rewards(rewardId):
    checked_reward = Reward.query.get(rewardId)
    checked_reward.is_claimed = not checked_reward.is_claimed
    if checked_reward.is_claimed == True:
        checked_reward.date = datetime.datetime.today()
        current_user.claimableRewards -= 1
    else:
        current_user.claimableRewards += 1
    db.session.commit()
    return redirect(url_for("views.rewards"))


@views.route('/edit-reward/<int:rewardId>', methods=['GET', 'POST'])
def edit_rewards(rewardId):
    reward = Reward.query.get(rewardId)
    if request.method == "POST":
        reward.data = request.form['reward']
        db.session.commit()
        return redirect(url_for("views.rewards"))
    else:
        return render_template("edit-reward.html", reward=reward, user=current_user)


@views.route('/delete-reward/<int:rewardId>')
def delete_rewards(rewardId):
    reward = Reward.query.get(rewardId)
    if reward:
        if reward.user_id == current_user.id:
            db.session.delete(reward)
            db.session.commit()
            flash('Reward deleted', category='error')
    
    return redirect(url_for("views.rewards"))

@views.route('/update-value', methods=['POST'])
def update_value():
    if request.method == 'POST':
        if 'dailyXp_update' in request.form:
            updatedDailyXpValue = int(request.form['dailyXp_update'])
            if updatedDailyXpValue >= current_user.weeklyXpValue:
                flash('Daily XP task value has to be lower than weekly XP task value!', category='error')
            else:
                current_user.dailyXpValue = updatedDailyXpValue
        if 'weeklyXp_update' in request.form:
            updatedWeeklyXpValue = int(request.form['weeklyXp_update'])
            if updatedWeeklyXpValue <= current_user.dailyXpValue:
                flash('Weekly XP task value has to be higher than daily XP task value!', category='error')
            elif updatedWeeklyXpValue >= current_user.monthlyXpValue:
                flash('Weekly XP task value has to be lower than monthly XP task value')
            else:
                current_user.weeklyXpValue = updatedWeeklyXpValue
        if 'monthlyXp_update' in request.form:
            updatedMonthlyXpValue = int(request.form['monthlyXp_update'])
            if updatedMonthlyXpValue <= current_user.weeklyXpValue:
                flash('Monthly Xp task value has to be higher than weekly XP task value!', category='error')
            current_user.monthlyXpValue = updatedMonthlyXpValue
        if 'levelRequirement_update' in request.form:
            current_user.levelRequirement = request.form['levelRequirement_update']
        db.session.commit()
    
    return redirect(url_for('views.profile'))

website/templates/edit-reward.html
{% extends "base.html" %}
{% block content %}
<br/>
<div align="center">
    <h1 class="title is-1">Edit your reward</h1>
    <form action="{{ url_for('views.edit_rewards', rewardId=reward.id) }}" method="post">
        <input type="text" name="reward" value="{{ reward.data }}">
        <button type="submit" class="btn btn-success">Save</button>
    </form>
</div>
{% endblock %}

website/templates/edit-task.html
{% extends "base.html" %}
{% block content %}
<br/>
<div align="center">
    <h1 class="title is-1">Edit your task</h1>
    <form action="{{ url_for('views.edit_tasks', taskId=task.id) }}" method="post">
        <input type="text" name="task" value="{{task.data }}">
        <button type="submit" class="btn btn-success">Save</button>
    </form>
</div>
{% endblock %}

website/templates/edit.html
{% extends "base.html" %}
{% block content %}
<br/>
<div align="center">
    <h1>Edit your task</h1>
    <form action="{{ url_for('views.edit_tasks', taskId=task.id) }}" method="post">
        <input type="text" name="task" value="{{task.data }}">
        <button type="submit" class="btn btn-success">Save</button>
    </form>
</div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %}

{% block content %}
<br>
<h1 align="center"  class="title is-1">
    <span class="icon is-small">
        <i class="fas fa-home" aria-hidden="true"></i>
    </span> &nbsp;Home
</h1>
<br/>
<div align="center">
<h5 class="title is-4 is-spaced"> Welcome to the home page of David's Habit Tracker! </h5>
</div>

<br/>

<div align="center">
    <h5 class="title is-4 is-spaced"> Quick introduction: </h5>
    <p class="subtitle">There are four tabs in total that can be accessed using the buttons above or the navbar in the top.</p>
    <p class="subtitle">The website itself has two main functions, with the Task Tracker being the main one:</p>
</div>

<br/>
<br/>

<div class="tile is-parent">
    <div class="tile is-child notification is-link">
        <h3 class="title is-3"> 
            <span class="icon is-small">
                <i class="fas fa-tasks" aria-hidden="true"></i>
            </span>
            &nbsp;
            <a href="{{ url_for('views.task') }}"> Task Tracker </a>
        </h3>
        <p> Track daily, weekly or monthly tasks. </p>
        <p> Earn XP to level up & claim rewards for each Level-Up </p>
    </div>
    &nbsp;
    &nbsp;
    <div class="tile is-child notification is-link">
        <h3 class="title is-3"> 
            <span class="icon is-small">
                <i class="fas fa-sticky-note" aria-hidden="true"></i>
            </span>
            &nbsp;
            <a href="{{ url_for('views.notes') }}"> Notes </a>
        </h3>
        <p> Add Notes or Reminders to a list</p>
        <p> Sorted by Date added </p>
    </div>
</div>

<br/>
<br/>

<div align="center">
    <br/>
    <p class="subtitle">The other functions are related to the Task Tracker functionality:</p>
</div>

<br/>
<br/>
<br/>

<div class="tile is-parent">
    <div class="tile is-child notification is-success">
        <h3 class="title is-3"> 
            <span class="icon is-small">
                <i class="fas fa-gift" aria-hidden="true"></i>
            </span>
            &nbsp;
            <a href="{{ url_for('views.rewards') }}"> Reward Center </a> 
        </h3>
        <p> Add custom rewards & claim them at every Level-Up.</p>
        <p>&nbsp;</p>
        <p> You can also see the Reward History, with each Reward being listed along with the date it was added</p>
    </div>
    &nbsp;
    &nbsp;
    <div class="tile is-child notification is-success">
        <h3 class="title is-3"> 
            <span class="icon is-small">
                <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            &nbsp;
            <a href="{{ url_for('views.profile') }}"> Profile </a>
        </h3>
        <p> Displays various information about the User </p>
        <p> This includes current and total XP, the number of completed tasks and the current level. </p>
        <p> You can also set custom XP rewards for all task types and a custom XP requirement for each level there</p>
    </div>
</div>

{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}


{% block content %}

<br/>

<form method="POST">
    <h3  class="title is-3" align="center">Login</h3>
    <div class="form-group">
        <label for="userName">User Name</label>
        <input 
            type="userName" 
            class="form-control" 
            id="userName" 
            name="userName" 
            placeholder="Enter User Name"
        />
    </div>
        <div class="form-group">
            <label for="password1">Password</label>
            <input 
                type="password" 
                class="form-control" 
                id="password1" 
                name="password1" 
                placeholder="Enter password"
            />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
</form>

{% endblock %}

website/templates/notes.html
{% extends "base.html" %} {% block title %}Notes{% endblock %}

{% block content %}

<h1 class="title is-1" align="center">Notes</h1>
<ul class="list-group list-group-flush" id="notes">
    {% for note in user.notes %}
    <li class="list-group-item">
        {{ note.data }}
        <button type="button" class="close" onClick="deleteNote('{{ note.id }}')">
            <span aria-hidden="true">&times;</span>
        </button>
    </li>
    {% endfor%}
</ul>
<form method="POST">
    <textarea name="note" id="note" class="form-control"></textarea>
    <br/>
    <div align="center">
        <button type="submit" class="btn btn-primary">Add Note</button>
    </div>
</form>
{% endblock %}

website/templates/profile.html
{% extends "base.html" %}

{% block content %}

<br/>

<h1 align="center" class="title is-size1">Your Profile</h1>
<br/>
<div align="center">
    <li class="list-group-item">
    <h3 class="title is-3">User Name - {{ user.userName }}</h3>
    <h3 class="title is-3">First Name - {{ user.first_name }}</h3>
    </li>
</div>

<br/>

<nav class="level is-mobile">
    <div class="level-item has-text-centered">
        <div>
            <p class="heading is-size-6">Current XP</p>
            <p class="title">{{ user.currentXp }}</p>
        </div>
    </div>
    <div class="level-item has-text-centered">
        <div>
            <p class="heading is-size-6">Total XP</p>
            <p class="title">{{ user.totalXp }}</p>     
    </div>
    </div>
    <div class="level-item has-text-centered">
        <div>
            <p class="heading is-size-6">Completed Tasks</p>
            <p class="title">{{ user.tasksCompleted }}</p>
        </div>
    </div>
    <div class="level-item has-text-centered">
        <div>
            <p class="heading is-size-6">Current Level</p>
            <p class="title">{{ user.level }}</p>
        </div>
    </div>
</nav>

<br/>

<div align="center">
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <h3 class="title is-size-3"> Set your custom XP rewards here</h3>
            <form action="{{ url_for('views.update_value') }}" method="post">
                <input type="text" name='dailyXp_update' id='dailyXp_update' data-indicator="newDailyXp" placeholder="Enter daily task XP" style="height: 34px">
                <button type="submit" class="btn btn-success">
                    <span class="icon is-small">
                        <i class="fas fa-sync" aria-hidden="true"></i>
                    </span>Update value
                </button> Standard value: 10 XP
            </form>
            Current value: {{current_user.dailyXpValue}}
            <br/>
            <br/>
            <form action="{{ url_for('views.update_value') }}" method="post">
                <input type="text" name='weeklyXp_update' id='weeklyXp_update' data-indicator="newWeeklyXp" placeholder="Enter weekly task XP" style="height: 34px">
                <button type="submit" class="btn btn-success">
                    <span class="icon is-small">
                        <i class="fas fa-sync" aria-hidden="true"></i>
                    </span>Update value
                </button> Standard value: 25 XP
            </form>
            Current value: {{current_user.weeklyXpValue}}
            <br/>
            <br/>
            <form action="{{ url_for('views.update_value') }}" method="post">
                <input type="text" name='monthlyXp_update' id='monthlyXp_update' data-indicator="newMonthlyXp" placeholder="Enter monthly task XP" style="height: 34px">
                <button type="submit" class="btn btn-success">
                    <span class="icon is-small">
                        <i class="fas fa-sync" aria-hidden="true"></i>
                    </span>Update value
                </button> Standard value: 50 XP
            </form>
            Current value: {{current_user.monthlyXpValue}}
        </li>
    </ul>
</div>

<br/>

<div align="center">
    <h3 class="title is-size-3 is-spaced"> Set your custom XP per level here</h3>
    <form action="{{ url_for('views.update_value') }}" method="post">
        <input type="text" name='levelRequirement_update' id='levelRequirement_update' placeholder="Enter XP requirement" style="height: 34px">
        <button type="submit" class="btn btn-success">
            <span class="icon is-small">
                <i class="fas fa-sync" aria-hidden="true"></i>
            </span>Update value
        </button> Standard value: 500 XP
    </form>
    Current value: {{current_user.levelRequirement}}
    <br/>
    <br/>
    <p>
        <h4  class="title is-size-4 is-family-code" style="color:Red;">Warning: This could mess with your level progress.</h4>
        <h6  class="title is-size-6 is-family-code" style="color:Red;">It is recommended to be set only once in the beginning.</h6>
    </p>
</div>



{% endblock %}

website/templates/rewards.html
{% extends "base.html" %}
{% block content %}
<br/>
<div align="center">
    <h1 class="title is-1"> Your Reward Center </h1>
    <br/>
    <h2 class="title is-3"> Current Level</h2>
    <h2 class="title is-3"> {{ user.level }} </h2>
    <br/>
    {% if user.claimableRewards <= 0 %}
    <h3 class="title is-3" style="color: red;"> You can not claim any rewards right now </h3>
    <h4 class="title is-4">The next reward can be claimed in {{ 1 - user.claimableRewards}} levels</h4>
    {% endif %}
    {% if user.claimableRewards > 0 %}
    <h3 class="title is-3" style="color: green;"> You can currently claim a reward !</h3>
    <h4 class="title is-4">You can still claim {{ user.claimableRewards }} rewards</h4>
    {% endif %}
    <br/>
</div>

<br/>

<div align="center">
    <h2 class="title is-2"><i class="fas fa-gift" aria-hidden="true"></i> Next Rewards</h2>
    <ul class="list-group list-group-flush">
        {% for reward in user.rewards %}
        {% if reward.is_claimed == False %}
            <li class="list-group-item">
                {% if user.claimableRewards > 0 %}
                <a href="{{ url_for('views.check_rewards', rewardId=reward.id) }}">
                    <button type="button" class="btn btn-sm btn-success">
                        <i class="fas fa-check"> Claim reward </i>
                    </button>
                </a>
                {% endif %}
                <span>&nbsp; {{ reward.data }} &nbsp;</span>
                <a href="{{ url_for('views.edit_rewards', rewardId = reward.id)}}">
                    <button type="button" class="btn btn-sm btn-warning">
                        <i class="fas fa-edit"></i> 
                    </button>
                </a>
                </button>
                <a href="{{ url_for('views.delete_rewards', rewardId = reward.id)}}">
                    <button type="button" class="btn btn-sm btn-danger">
                        <i class="fas fa-trash"></i> 
                    </button>
                </a>
                </button>
            </li>
        {% endif %}
        {% endfor %}
    </ul>
    <br/>
        <form action="{{ url_for('views.add_rewards')}}" method="post">
            <input type="text" name='reward'>
            <button type="submit" class="btn btn-success">
                <span class="icon is-small">
                    <i class="fas fa-plus" aria-hidden="true"></i>
                </span>Add reward
            </button>
        </form>
    </div>
    
    <br/>

<div align="center">    
    <h3 class="title is-3"> Reward history </h3>
    {% for reward in user.rewards %}
    {% if reward.is_claimed == True %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Reward claimed</th>
                <th scope="col" class="text-center">Claimed at</th>
                <th scope="col" class="text-right text-truncate"> Unclaim reward </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td scope="row" class="text-left">{{ reward.data }}</th>
                <td class="text-center text-truncate">{{ reward.date.strftime("%d.%m.%Y %H:%M") }}</td>
                <td class="text-right">
                    <a href="{{ url_for('views.check_rewards', rewardId=reward.id) }}">
                        <button type="button" class="btn btn-sm btn-warning">
                            <i class="fas fa-undo"> </i>
                        </button>
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
    {% endif %}
    {% endfor %}
</div>

{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %}

{% block content %}

<br/>

<form method="POST">
    <h3  class="title is-3" align="center">Sign Up</h3>
    <div class="form-group">
        <label for="userName">User Name</label>
        <input 
            type="userName" 
            class="form-control" 
            id="userName" 
            name="userName" 
            placeholder="Enter User Name"
        />
    </div>
    <div class="form-group">
        <label for="firstName">First Name</label>
        <input 
            type="text" 
            class="form-control" 
            id="firstName" 
            name="firstName" 
            placeholder="Enter first name"
        />
    </div>
    <div class="form-group">
        <label for="password1">Password</label>
        <input 
            type="password" 
            class="form-control" 
            id="password1" 
            name="password1" 
            placeholder="Enter password"
        />
    </div>
    <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input 
            type="password" 
            class="form-control" 
            id="password2" 
            name="password2" 
            placeholder="Confirm password"
        />
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

website/templates/tasks.html
{% extends "base.html" %} {% block title %}Tasks{% endblock %}

{% block content %}

<br/>

<div align="center" class="page-header">
    <div>
        <span>
            <h1 class="title is-1"><i class="fas fa-tasks" aria-hidden="true"></i> Your Tasks</h1>
        </span>
    </div>
</div>
<br/>
<br/>
<div align="center">
<h2 class="title is-2"><i class="fas fa-sun" aria-hidden="true"></i> Daily Tasks</h2>
<ul class="list-group list-group-flush">
    {% for task in user.tasks %}
    {% if task.xp == user.dailyXpValue %}
        <li class="list-group-item">
            {% if task.is_done %}
                <i class="far fa-check-square" style="font-size: 20px;"></i>
            {% endif %}
            {% if task.is_done == False %}
                <i class="far fa-square" style="font-size: 20px;"></i>
            {% endif %}
            <span {% if task.is_done %} style="text-decoration: line-through" {% endif %}> &nbsp;{{ task.data }}</span>
            <a href="{{ url_for('views.check_tasks', taskId = task.id)}}">
                <button type="button" class="btn btn-sm btn-success">
                    <i class="fas fa-check"></i>
                </button>
            </a>
            
            <a href="{{ url_for('views.edit_tasks', taskId = task.id)}}">
                <button type="button" class="btn btn-sm btn-warning">
                    <i class="fas fa-edit"></i> 
                </button>
            </a>
            
            <a href="{{ url_for('views.delete_tasks', taskId = task.id)}}">
                <button type="button" class="btn btn-sm btn-danger">
                    <i class="fas fa-trash"></i> 
                </button>
            </a>
            
        </li>
    {% endif %}
    {% endfor %}
</ul>
<br/>
    <form action="{{ url_for('views.add_task', taskXp = user.dailyXpValue)}}" method="post">
        <input type="text" style="text-align: center;" name='task' placeholder="Enter task name here" style="height: 34px">
        <button type="submit" class="btn btn-success">
            <span class="icon is-small">
                <i class="fas fa-plus" aria-hidden="true"></i>
            </span> Add task
        </button>
    </form>
</div>

<br/>
<br/>

<div align="center">
    <h2 class="title is-2"><i class="fas fa-calendar-week" aria-hidden="true"></i> Weekly Tasks</h2>
    <ul class="list-group list-group-flush">
        {% for task in user.tasks %}
        {% if task.xp == user.weeklyXpValue %}
        <li class="list-group-item">
            {% if task.is_done %}
                <i class="far fa-check-square" style="font-size: 20px;"></i>
            {% endif %}
            {% if task.is_done == False %}
                <i class="far fa-square" style="font-size: 20px;"></i>
            {% endif %}
            <span {% if task.is_done %} style="text-decoration: line-through" {% endif %}> &nbsp;{{ task.data }}</span>
            <a href="{{ url_for('views.check_tasks', taskId = task.id)}}">
                <button type="button" class="btn btn-sm btn-success">
                    <i class="fas fa-check"></i>
                </button>
            </a>
            
            <a href="{{ url_for('views.edit_tasks', taskId = task.id)}}">
                <button type="button" class="btn btn-sm btn-warning">
                    <i class="fas fa-edit"></i> 
                </button>
            </a>
            
            <a href="{{ url_for('views.delete_tasks', taskId = task.id)}}">
                <button type="button" class="btn btn-sm btn-danger">
                    <i class="fas fa-trash"></i> 
                </button>
            </a>
            
        </li>
        {% endif %}
        {% endfor %}
    </ul>
    <br/>
        <form action="{{ url_for('views.add_task', taskXp = user.weeklyXpValue) }}" method="post">
            <input type="text" style="text-align: center;" name='task' placeholder="Enter task name here" style="height: 34px">
            <button type="submit" class="btn btn-success">
                <span class="icon is-small">
                    <i class="fas fa-plus" aria-hidden="true"></i>
                </span> Add task
            </button>
        </form>
    </div>

<br/>
<br/>

<div align="center">
    <h2 class="title is-2"><i class="fas fa-calendar-check" aria-hidden="true"></i> Monthly Tasks</h2>
    <ul class="list-group list-group-flush">
        {% for task in user.tasks %}
        {% if task.xp == user.monthlyXpValue %}
            <li class="list-group-item">
                {% if task.is_done %}
                    <i class="far fa-check-square" style="font-size: 20px;"></i>
                {% endif %}
                {% if task.is_done == False %}
                    <i class="far fa-square" style="font-size: 20px;"></i>
                {% endif %}
                <span {% if task.is_done %} style="text-decoration: line-through" {% endif %}> &nbsp;{{ task.data }}</span>
                <a href="{{ url_for('views.check_tasks', taskId = task.id)}}">
                    <button type="button" class="btn btn-sm btn-success">
                        <i class="fas fa-check"></i>
                    </button>
                </a>
                
                <a href="{{ url_for('views.edit_tasks', taskId = task.id)}}">
                    <button type="button" class="btn btn-sm btn-warning">
                        <i class="fas fa-edit"></i> 
                    </button>
                </a>
                
                <a href="{{ url_for('views.delete_tasks', taskId = task.id)}}">
                    <button type="button" class="btn btn-sm btn-danger">
                        <i class="fas fa-trash"></i> 
                    </button>
                </a>
                
            </li>
        {% endif %}
        {% endfor %}
    </ul>
    <br/>
        <form action="{{ url_for('views.add_task', taskXp = user.monthlyXpValue) }}" method="post">
            <input type="text" style="text-align: center;" name='task' placeholder="Enter task name here" style="height: 34px">
            <button type="submit" class="btn btn-success">
                <span class="icon is-small">
                    <i class="fas fa-plus" aria-hidden="true"></i>
                </span> Add task
            </button>
        </form>
    </div>

<br/>
<br/>

<div align="center">
    <h1 class="title is-1">Current XP</h1>
    <h2 class="title is-2">{{ user.currentXp }}/{{ user.levelRequirement }}</h2>
    <br/>
    <h4 class="title is-4"> Level progress:</h4>
    <h4 class="title is-4"> {{user.level_progress}} </h4>
    <br/>
    <h3 class="title is-3">Level {{ current_user.level }}</h3>
</div>
<br/>
<progress class="progress is-success" value="{{user.currentXp}}" max="{{user.levelRequirement}}">{{user.level_progress}}%</progress>
<br/>

<div align="center">
    <h1 class="title is-1">Total XP</h1>
    <h2 class="title is-2">{{ user.totalXp }}</h2>
</div>

<br/>

{% endblock %}